INSERT INTO USUARIO (NOME, EMAIL, SENHA)
VALUES('FULANO ALVES DA SILVA','fulano@teste.com.br', '12345');

INSERT INTO USUARIO (NOME, EMAIL, SENHA)
VALUES('CICRANO DE SOUZA','cicrano@teste.com.br', '12345');